[book]
title = "pedantix"
description = "The pedantic Nix formatter"
authors = ["Leon Schwarzäugl"]
language = "en"
src = "src"

[output.html]
default-theme = "navy"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/swarsel/pedantix"
edit-url-template = "https://github.com/swarsel/pedantix/edit/main/docs/{path}"
additional-css = ["theme/pedantix.css"]

[output.html.fold]
enable = true
level = 1

[output.html.search]
enable = true
