;;; gen-emacs-docs.el --- Emit the Emacs reference for the docs -*- lexical-binding: t; -*-
;;; Commentary:
;; Loads pedantix.el and prints Markdown tables for its interactive commands
;; and `defcustom' variables, so the Emacs docs stay in sync with the source.
;; Run in batch: emacs --batch -l docs/gen-emacs-docs.el
;;; Code:

(require 'cl-lib)

(defun pedantix-docs--first-line (doc)
  "Return the first line of DOC, escaped for a Markdown table cell."
  (let ((line (car (split-string (or doc "") "\n"))))
    (replace-regexp-in-string "|" "\\\\|" line)))

(defun pedantix-docs--commands ()
  "Print a Markdown table of pedantix's interactive commands."
  (princ "### Commands\n\n")
  (princ "| Command | Description |\n")
  (princ "|---------|-------------|\n")
  (let (rows)
    (mapatoms
     (lambda (sym)
       (when (and (commandp sym)
                  (string-prefix-p "pedantix-" (symbol-name sym)))
         (push sym rows))))
    (dolist (sym (cl-sort rows #'string< :key #'symbol-name))
      (princ (format "| `M-x %s` | %s |\n"
                     sym (pedantix-docs--first-line (documentation sym)))))
    (princ "\n")))

(defun pedantix-docs--customs ()
  "Print a Markdown table of pedantix's `defcustom' variables."
  (princ "### Customization\n\n")
  (princ "| Variable | Default | Description |\n")
  (princ "|----------|---------|-------------|\n")
  (let (rows)
    (mapatoms
     (lambda (sym)
       (when (and (custom-variable-p sym)
                  (string-prefix-p "pedantix-" (symbol-name sym))
                  ;; Skip the hook auto-generated by `define-minor-mode'.
                  (not (string-suffix-p "-hook" (symbol-name sym))))
         (push sym rows))))
    (dolist (sym (cl-sort rows #'string< :key #'symbol-name))
      (princ (format "| `%s` | `%s` | %s |\n"
                     sym
                     (prin1-to-string (default-value sym))
                     (pedantix-docs--first-line
                      (documentation-property sym 'variable-documentation)))))
    (princ "\n")))

(let* ((this (or load-file-name buffer-file-name))
       (root (file-name-directory (directory-file-name (file-name-directory this)))))
  (load (expand-file-name "emacs/pedantix.el" root) nil t))

(pedantix-docs--commands)
(pedantix-docs--customs)

;;; gen-emacs-docs.el ends here
